name: VPN Auto‑Parser

on:
  schedule:
    # каждые 30 минут
    - cron: '*/30 * * * *'
  workflow_dispatch:   # ручной запуск

jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: cd parser && npm ci

      - name: Run parser
        run: cd parser && node index.js

      - name: Commit result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add vpn_filtered.txt
          git commit -m "Auto‑update filtered configs $(date -u '+%Y-%m-%d %H:%M UTC')" || echo "No changes"
          git push