name: Scheduled VPN Parser
permissions:
  contents: write  # Важно для коммита
  pull-requests: write
  issues: write
on:
  schedule:
    - cron: '0 0,13 * * *'
  workflow_dispatch:
jobs:
  run-parser:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run parser
        run: node index.js
      - name: Commit results if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(parser): update filtered_list.txt from scheduled run"
          file_pattern: "results/*"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_fetch: true
          skip_checkout: true
