name: Scheduled VPN Parser

on:
  schedule:
    # every 12 hours: at 00:00 and 12:00 UTC
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  run-parser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run parser
        run: node index.js
      - name: Commit results if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(parser): update filtered_list.txt from scheduled run"
          file_pattern: "results/*"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          branch: "main"
